### ISSUE TITLE
Add ability to include "\n" string in input file

### ISSUE THREAD

**Issue by rahji** [kkew3/tabulate#2]
It would be really useful to be able to have multiple lines in each cell of the table - eg: for creating a paragraph followed by a numbered list. This could be accomplished by allowing the newline escape sequence in the text of the input file. Sorry, I am really not a Python guy or I would submit a PR. 😬

**Comment by kkew3** [comment]
Good point! I'll look into that.

**Comment by kkew3** [comment]
I find it hard to systematically support escape sequences like `echo -e`. However, this may be achieved instead by customizing the table row separator while reading table from the input, e.g. using `<EOL>\n` rather than `\n` as row separator. I haven't investigate the feasibility carefully, but it should be doable. I'll work on this in the next release. PR is also welcome.

**Comment by kkew3** [comment]
You may now use option `-e` to parse for `\n` etc. in the input. I'll close this issue. Please, comment below if you have any problem with this option.
